//4 Categories Question and Answers
//
   //  Pipe and cistern Category
   const qstnAns = [
    {
      id: "pc1",
      question: "Two pipes A & B can fill a tank in 5 min & 10 min respectively. Both the pipes are opened together but after 2 min, pipe A is turned off. What is the total time required to fill the tank?",
      a: "4 mins",
      b: "6 mins",
      c: "14 mins",
      d: "20 mins",
      answer: "b",
    },
    {
      id: "pc2",
      question: "It is observed that the pipe A can fill the tank in 15 hrs and the same tank is filled by pipe B in 20 hrs. The third pipe C can vacant the tank in 25 hrs. If all the pipes get opened initially and after 10 hrs, the pipe C is closed, then how long will it take to fill the tank?",
      a: "17 hrs",
      b: "12 hrs",
      c: "8 hrs",
      d: "3 hrs",
      answer: "b",
    },
    {
      id: "pc3",
      question: "Two pipes can fill a tank in 8 hrs & 6 hrs respectively. If they are opened on alternate hours and if pipe A gets opened first, then in how many hours, the tank will be full?",
      a: "4 hrs",
      b: "5 hrs",
      c: "6 hrs",
      d: "7 hrs",
      answer: "d",
    },
    {
      id: "pc4",
      question: "If two pipes function simultaneously, the reservoir will be filled in 24 hrs. One pipe fills the reservoir 20 hours faster than the other. How many hours does it take for the second pipe to fill the reservoir?",
      a: "11/5 hrs",
      b: "23 hrs",
      c: "60 hrs",
      d: "44/5 hrs",
      answer: "c",
    },
    {
      id: "pc5",
      question: "Two pipes fills a cistern in 15 hrs and 20 hrs respectively. The pipes are opened simultaneously and it is observed that it took 26 min more to fill the cistern because of leakage at the bottom. If the cistern is full, then in what time will the leak empty it?",
      a: "180 hrs ",
      b: "70 hrs ",
      c: "300 hrs ",
      d: "28 hrs",
      answer: "a",
    },
    {
      id: "pc6",
      question: "An electric pump can fill a tank in 4 hours. Due to leakage in the tank, it took 4(1/2) hrs to fill the tank. If the tank is full, how much time will the leak take to empty the full tank?",
      a: "21 hrs",
      b: "9 hrs",
      c: "5 hrs",
      d: "36 hrs",
      answer: "d",
    },
    {
      id: "pc7",
      question: "A booster pump can be used to fill as to empty the tank. The capacity of the tank is 1200 m3. The emptying capacity of the tank is 10 m3 per minute higher than its filling capacity and the pump requires 4 minutes lesser to vacant the tank than it requires to fill it. Calculate the filling capacity of the pump.",
      a: "15 hrs",
      b: "50 hrs",
      c: "35 hrs",
      d: "100 hrs",
      answer: "b",
    },
    {
      id: "pc8",
      question: "Two pipes can fill a tank in 10 and 14 minutes respectively and a waste pipe can empty 4 gallons per minute. If all the pipes working together can fill the tank in 6 minutes, what is the capacity of the tank?",
      a: "840 gallons",
      b: "400 gallons",
      c: "215 gallons",
      d: "120 gallons",
      answer: "a",
    },
    {
      id: "pc9",
      question: "Two pipes can fill a tank in 6 hours and 8 hours respectively while a third pipe empties the full tank in 12 hours. If all the three pipes operate simultaneously, in how much time will the tank be filled?",
      a: "7 hrs",
      b: "11 (1/5)",
      c: "4(4/5) hrs",
      d: "6 hrs",
      answer: "c",
    },
    {
      id: "pc10",
      question: "Two pipes A & B can fill the tank in 12 hours and 36 hours respectively. If both the pipes are opened simultaneously, how much time will be required to fill the tank?",
      a: "9 hrs",
      b: "7 hrs",
      c: "19 hrs",
      d: "16 hrs",
      answer: "a",
    },
  
   //Probability Category
  
    {
      id: "probabi1",
      question: "What is the probability that a leap year has 53 Saturdays and 52 Sundays?",
      a: "1/7",
      b: "1/3",
      c: "3/4",
      d: "5/8",
      answer: "a",
    },
    {
      id: "probabi2",
      question: "The probability of success of three students X, Y and Z in the one examination are 1/5, 1/4 and 1/3 respectively. Find the probability of success of at least two.",
      a: "1/2",
      b: "6/3",
      c: "1/6",
      d: "5/2",
      answer: "c",
    },
    {
      id: "probabi3",
      question: "If two dice are thrown together, the probability of getting an even number on one die and an odd number on the other is?",
      a: "0",
      b: "1/2",
      c: "1",
      d: "1/2",
      answer: "b",
    },
    {
      id: "probabi4",
      question: "Ajay rolled two dice together. What is the probability that first dice showed a multiple of 3 and the second dice showed an even number?",
      a: "5/6",
      b: "1/3",
      c: "1/6",
      d: "1/9",
      answer: "c",
    },
    {
      id: "probabi5",
      question: "Two unbiased dice are rolled simultaneously. Find the probability of getting sum greater than 5.",
      a: "13/18",
      b: "23/36",
      c: "7/9",
      d: "5/9",
      answer: "a",
    },
    {
      id: "probabi6",
      question: "An unbiased die is tossed.Find the probability of getting a multiple of 3.",
      a: "5/7",
      b: "1/2",
      c: "3/4",
      d: "1/3",
      answer: "d",
    },
    {
      id: "probabi7",
      question: "Two unbiased dice are rolled simultaneously. Find the probability of getting sum greater than 5.",
      a: "13/18",
      b: "23/36",
      c: "7/9",
      d: "5/9",
      answer: "a",
    },
    {
      id: "probabi8",
      question: "In a simultaneous throw of two dice, what is the probability of getting a doublet?",
      a: "7/3",
      b: "3/2",
      c: "1/6",
      d: "1/8",
      answer: "c",
    },
    {
      id: "019",
      question: "If P(A)=4/9;then the odd against the event A is?",
      a: "4:9",
      b: "5:4",
      c: "4:5",
      d: "2:3:",
      answer: "b",
    },
    {
      id: "probabi10",
      question: "What is the probability that a leap year selected at random, will contain 53 sundays?",
      a: "4/7",
      b: "1/7",
      c: "2/7",
      d: "3/7",
      answer: "c",
    },
 
  
   //Problem on age Category
    {
      id: "age1",
      question: "Seven years ago, the ratio of the age of A and B is 8: 9. After 7 years, the ratio of the age of A and B is 10: 11. After 'x' years from now, the age of B is 15/14 of the age of A. Find the value of 'x'.",
      a: "30 Years",
      b: "35 Years",
      c: "28 Years",
      d: "44 Years",
      answer: "b",
    },
    {
      id: "age2",
      question: "The sum of the ages of Neeraj and Suresh is twice the sum of their ages 6 years ago. What is Suresh's age, if Neeraj is 10 years older than Suresh?",
      a: "3 Years",
      b: "4 Years",
      c: "7 Years",
      d: "9 Years",
      answer: "c",
    },
    {
      id: "age3",
      question: " The ratio between the present ages of P and Q is 6:7. If Q is 4 years old than P, what will be the ratio of the ages of P and Q after 4 years",
      a: "7:8",
      b: "8:7",
      c: "4:5",
      d: "3:2",
      answer: "a",
    },
    {
      id: "age4",
      question: "Ages of two persons differ by 16 years. If 6 year ago, the elder one be 3 times as old the younger one, find their present age",
      a: "17, 23",
      b: "14,30",
      c: "5, 16",
      d: "12,22",
      answer: "b",
    },
    {
      id: "age5",
      question: "Murali's present age is half of his father's age. before 10 years, his father's age was thrice his age. Find the present age of Murali and his father.",
      a: "16, 32 Years",
      b: "15, 30 Years",
      c: "20, 40 Years",
      d: "19, 31 Years",
      answer: "c",
    },
    {
      id: "age6",
      question: "The ratio of the present ages of a man and his wife is 5: 8. After 10 years, the ratio of the man and his wife will be 2: 3. What will be the ratio of their ages after 20 years?",
      a: "7:10",
      b: "3:5",
      c: "4:5",
      d: "9:10",
      answer: "a",
    },
    {
      id: "age7",
      question: "After 5 years, the ratio between ages of A and B will be 5: 8 and after 8 years, the sum of ages will be 71 years. Find the present age of B.",
      a: "33 Years",
      b: "40 Years",
      c: "35 Years",
      d: "32 Years",
      answer: "c",
    },
    {
      id: "age8",
      question: "After 15 years, a man will be just four times as old as he was 15 years ago. What is his present age?",
      a: "10 Years",
      b: "15 Years",
      c: "20 Years",
      d: "25 Years",
      answer: "d",
    },
    {
      id: "age9",
      question: "The ratio of ages of Rahul and his wife after 7 years from now will be 7: 6. If his wife was born 23 years ago, find the age of Rahul after 2 years?",
      a: "25",
      b: "30",
      c: "28",
      d: "40",
      answer: "b",
    },
    {
      id: "age10",
      question: "Four years ago, the age of the mother was 13 times the age of her daughter. Two years hence, the mother's age will be 4 times the daughter's age. After how many years will the mother's age be 3 times that of her daughter?",
      a: "4",
      b: "6",
      c: "5",
      d: "7",
      answer: "b",
    },
  
  
    //Profit and loss Category
    {
      id: "031",
      question: "A shopkeeper allows two successive discounts of X% on a shirt which is marked at Rs 2500 and sells it at Rs 1764. Find the selling price of the shirt if the shopkeeper would have given X + 2% of two equal successive discounts?",
      a: "1681",
      b: "2025",
      c: "1936",
      d: "1600",
      answer: "a",
    },
    {
      id: "032",
      question: "By selling an article for Rs 8,670 a man loses 15% At what price (in Rs) should he sell it in order to make a profit of 15%?",
      a: "13,370",
      b: "11,730",
      c: "18,590",
      d: "23,560",
      answer: "b",
    },
    {
      id: "033",
      question: "The cost price of 20 articles is the same as the selling price of X articles. If the profit is 25%, find out the value of X?",
      a: "13",
      b: "16",
      c: "8",
      d: "21",
      answer: "b",
    },
    {
      id: "034",
      question: "A bottle with the cost price of Rs. 4500 is marked x% above the cost price and sold after two successive discount of Rs. 140 and 10% respectively for a profit of Rs. 720. A jeans has cost price that is 20% less than that of the bottle. If the selling price of the jeans is Rs.4680 and it is sold at (x - k)% profit then find the value of k?",
      a: "1",
      b: "2",
      c: "3",
      d: "4",
      answer: "b",
    },
    {
      id: "034",
      question: "Rick bought cold drinks of Rs. 56000. Then he sold 1/3rd of the total purchase to a 40% loss. How much profit does he need to earn on the remaining cold drinks to cover the loss? ",
      a: "20%",
      b: "10%",
      c: "50%",
      d: "250%",
      answer: "a",
    },
    {
      id: "036",
      question: "A shopkeeper earns a profit of 25 percent on selling a radio at 15 percent. discount on the Printed price. Finds the ratio of the Printed price and the cost price of the radio.",
      a: "17:25",
      b: "25:27",
      c: "27:25",
      d: "25:17",
      answer: "d",
    },
    {
      id: "037",
      question: "A shopkeeper normally makes a profit of 20% in a certain transaction; he weights 900 g instead of 1 kg, due to an issue with the weighing machine. If he charges 10% less than what he normally charges, what is his actual profit or loss percentage?",
      a: "20%",
      b: "28%",
      c: "25%",
      d: "30%",
      answer: "a",
    },
    {
      id: "038",
      question: "Two successive discounts of 40% and 20%, respectively, on the marked price of an article are equal to single discount of Rs 988. The marked price (in Rs) of the article is:",
      a: "2470",
      b: "2200",
      c: "1900",
      d: "2070",
      answer: "c",
    },
    {
      id: "039",
      question: "A dishonest merchant sells goods at a 12.5% loss on the cost price, but uses 28 g weight instead of 36 g. What is his percentage profit or loss?",
      a: "6.25% loss",
      b: "12.5% gain",
      c: "18.75% gain",
      d: "10.5% loss",
      answer: "b",
    },
    {
      id: "040",
      question: "A shopkeeper marks his sarees at 20% above the cost price and allows the purchaser a discount of 10% for cash buying. What profit per cent does he make?",
      a: "18%",
      b: "38%",
      c: "8%",
      d: "28%",
      answer: "c",
    },
  
  
  ];
  